**GROUP 2**

Name
*  Alarcon Vargas, David Andres
*  Chaparro Pérez, David Felipe
*  Rincon Vija, Nicolas Mauricio

# Simple iteration for systems of linear equations

First, generate a random diagonally dominant matrix, for testing.

In [21]:
import numpy as np
rndm = np.random.RandomState(1234)

n = 10
A = rndm.uniform(size=(n, n)) + np.diagflat([15]*n)
b = rndm.uniform(size=n)

In [22]:
b

array([0.76711663, 0.70811536, 0.79686718, 0.55776083, 0.96583653,
       0.1471569 , 0.029647  , 0.59389349, 0.1140657 , 0.95080985])

In [23]:
A

array([[1.51915195e+01, 6.22108771e-01, 4.37727739e-01, 7.85358584e-01,
        7.79975808e-01, 2.72592605e-01, 2.76464255e-01, 8.01872178e-01,
        9.58139354e-01, 8.75932635e-01],
       [3.57817270e-01, 1.55009951e+01, 6.83462935e-01, 7.12702027e-01,
        3.70250755e-01, 5.61196186e-01, 5.03083165e-01, 1.37684496e-02,
        7.72826622e-01, 8.82641191e-01],
       [3.64885984e-01, 6.15396178e-01, 1.50753812e+01, 3.68824006e-01,
        9.33140102e-01, 6.51378143e-01, 3.97202578e-01, 7.88730143e-01,
        3.16836122e-01, 5.68098653e-01],
       [8.69127390e-01, 4.36173424e-01, 8.02147642e-01, 1.51437668e+01,
        7.04260971e-01, 7.04581308e-01, 2.18792106e-01, 9.24867629e-01,
        4.42140755e-01, 9.09315959e-01],
       [5.98092228e-02, 1.84287084e-01, 4.73552788e-02, 6.74880944e-01,
        1.55946248e+01, 5.33310163e-01, 4.33240627e-02, 5.61433080e-01,
        3.29668446e-01, 5.02966833e-01],
       [1.11894318e-01, 6.07193706e-01, 5.65944643e-01, 6.76406199e-03,
   

# I.  Jacobi iteration

Given

$$
A x = b
$$

separate the diagonal part $D$,

$$ A = D + (A - D) $$

and write

$$
x = D^{-1} (D - A) x + D^{-1} b\;.
$$

Then iterate

$$
x_{n + 1} = B x_{n} + c\;,
$$

where

$$
B = D^{-1} (A - D) \qquad \text{and} \qquad c = D^{-1} b
$$


Let's construct the matrix and the r.h.s. for the Jacobi iteration

In [24]:
diag_1d = np.diag(A)

B = -A.copy()
np.fill_diagonal(B, 0)

D = np.diag(diag_1d)
invD = np.diag(1./diag_1d)
BB = invD @ B
c = invD @ b

In [25]:
# sanity checks
from numpy.testing import assert_allclose

assert_allclose(-B + D, A)


# xx is a "ground truth" solution, compute it using a direct method
xx = np.linalg.solve(A, b)

np.testing.assert_allclose(A@xx, b)
np.testing.assert_allclose(D@xx, B@xx + b)
np.testing.assert_allclose(xx, BB@xx + c)

Check that $\| B\| \leqslant 1$:

In [26]:
np.linalg.norm(BB)

0.36436161983015336

### Do the Jacobi iteration

In [27]:
n_iter = 50

x0 = np.ones(n)
x = x0
for _ in range(n_iter):
    x = BB @ x + c

In [28]:
# Check the result:

A @ x - b

array([ 1.11022302e-16,  0.00000000e+00, -2.22044605e-16, -1.11022302e-16,
        1.11022302e-16,  0.00000000e+00, -2.42861287e-17,  0.00000000e+00,
       -2.77555756e-17,  1.11022302e-16])

### Task I.1

Collect the proof-of-concept above into a single function implementing the Jacobi iteration. This function should receive the r.h.s. matrix $A$, the l.h.s. vector `b`, and the number of iterations to perform.


The matrix $A$ in the illustration above is strongly diagonally dominant, by construction.
What happens if the diagonal matrix elements of $A$ are made smaller? Check the convergence of the Jacobi iteration, and check the value of the norm of $B$.

(20% of the total grade)


In [29]:
# ... ENTER YOUR CODE HERE ...
import numpy as np

def jacobi_iteration(M_A, V_b, num_iterations):
  n = M_A.shape[0]
  x = np.zeros(n)
  norms_diff = []
  norms_B = []
  for _ in range(num_iterations):
      x_new = np.zeros(n)
      for i in range(n):
          x_new[i] = (V_b[i] - np.dot(M_A[i, :i], x[:i]) - np.dot(M_A[i, i+1:], x[i+1:])) / M_A[i, i]
      norms_diff.append(np.linalg.norm(x_new - x))
      norms_B.append(np.linalg.norm(M_A - np.diag(np.diagonal(M_A))))

      x = x_new

  return x, norms_diff, norms_B

In [30]:
A = np.array([[7, 1, 1],
              [1, 8, 5],
              [1, 5, 9]])

b = np.array([1, 5, 6])

num_iterations = 10

In [31]:
x_orig, diff_orig, norm_B_orig = jacobi_iteration(A, b, num_iterations)

In [32]:
A_modified = np.array([[0.7, 0.1, 0.1],
                       [0.1, 0.8, 0.5],
                       [0.1, 0.5, 0.9]])
x_modified, diff_modified, norm_B_modified = jacobi_iteration(A_modified, b, num_iterations)


In [33]:
print('matriz original')
print(x_orig)
print(diff_orig)

print(norm_B_orig)

print('matriz modificada')
print(x_modified)
print(diff_modified)

print(norm_B_modified)

matriz original
[0.0259429  0.31264433 0.4827487 ]
[0.9249203250603538, 0.5955653862101966, 0.3795756829762065, 0.24489902652625958, 0.15635375893678347, 0.1007923899409298, 0.0644041091155266, 0.041489469087698225, 0.026529378746075756, 0.017080474264069775]
[7.3484692283495345, 7.3484692283495345, 7.3484692283495345, 7.3484692283495345, 7.3484692283495345, 7.3484692283495345, 7.3484692283495345, 7.3484692283495345, 7.3484692283495345, 7.3484692283495345]
matriz modificada
[0.25942903 3.12644329 4.82748699]
[9.249203250603538, 5.955653862101966, 3.7957568297620656, 2.448990265262597, 1.5635375893678343, 1.0079238994092972, 0.6440410911552651, 0.41489469087698144, 0.26529378746075644, 0.1708047426406971]
[0.7348469228349535, 0.7348469228349535, 0.7348469228349535, 0.7348469228349535, 0.7348469228349535, 0.7348469228349535, 0.7348469228349535, 0.7348469228349535, 0.7348469228349535, 0.7348469228349535]


# II. Seidel's iteration.

##### Task II.1

Implement the Seidel's iteration.

Test it on a random matrix. Study the convergence of iterations, relate to the norm of the iteration matrix.

(30% of the total grade)

In [34]:
# ... ENTER YOUR CODE HERE ...
import numpy as np

def gauss_seidel_iteration(A, b, num_iterations):
    n = A.shape[0]
    x = np.zeros(n)
    norms_diff = []
    norms_B = []
    for _ in range(num_iterations):
        x_new = np.zeros(n)
        for i in range(n):
            x_new[i] = (b[i] - np.dot(A[i, :i], x_new[:i]) - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]
        norms_diff.append(np.linalg.norm(x_new - x))
        norms_B.append(np.linalg.norm(A - np.tril(A) @ np.triu(A, 1)))

        x = x_new

    return x, norms_diff, norms_B

In [35]:
n = 7
A = np.random.rand(n, n)
b = np.random.rand(n)
num_iterations = 20

In [36]:
x, diff, norm_B = gauss_seidel_iteration(A, b, num_iterations)
print(x)
print(diff)
print(norm_B)

[ 2.03870148e+14  2.00217346e+15 -1.60267559e+15 -1.91785796e+15
  1.11181280e+16 -6.65907650e+15 -3.43561404e+15]
[4.463360375058404, 28.620924338842695, 195.55323133973798, 1284.2415901444404, 8323.90493485999, 53767.43927648771, 347003.15059726796, 2238989.614449105, 14445970.07902936, 93204159.24323936, 601343128.2316601, 3879797227.8848257, 25032003323.66927, 161503583445.54047, 1042002382358.2974, 6722878451534.806, 43375231572398.16, 279851960302368.34, 1805572370257664.5, 1.1649343390945288e+16]
[4.457301786507906, 4.457301786507906, 4.457301786507906, 4.457301786507906, 4.457301786507906, 4.457301786507906, 4.457301786507906, 4.457301786507906, 4.457301786507906, 4.457301786507906, 4.457301786507906, 4.457301786507906, 4.457301786507906, 4.457301786507906, 4.457301786507906, 4.457301786507906, 4.457301786507906, 4.457301786507906, 4.457301786507906, 4.457301786507906]


# III. Minimum residual scheme

### Task III.1

Implement the $\textit{minimum residual}$ scheme: an explicit non-stationary method, where at each step you select the iteration parameter $\tau_n$ to minimize the residual $\mathbf{r}_{n+1}$ given $\mathbf{r}_n$. Test it on a random matrix, study the convergence to the solution, in terms of the norm of the residual and the deviation from the ground truth solution (which you can obtain using a direct method). Study how the iteration parameter $\tau_n$ changes as iterations progress.

(50% of the grade)

In [37]:
# ... ENTER YOUR CODE HERE ...
def minres_scheme(A, b, num_iterations):
    n = A.shape[0]
    x = np.zeros(n)
    r = b - A @ x
    p = r.copy()
    norms_resid = []
    norms_deviation = []
    tau_values = []

    for k in range(num_iterations):
        Ap = A @ p
        denom = np.dot(p, Ap)
        if denom == 0:
            break
        tau = np.dot(r, Ap) / denom
        x_new = x + tau * p
        r_new = r - tau * Ap
        norms_resid.append(np.linalg.norm(r_new))
        norms_deviation.append(np.linalg.norm(x_new - x))
        tau_values.append(tau)
        x = x_new
        r = r_new
        beta = np.linalg.norm(r)
        p = r + (beta / np.linalg.norm(r)) * p

    return x, norms_resid, norms_deviation, tau_values

In [38]:
n = 7
A = np.random.rand(n, n)
b = np.random.rand(n)
num_iterations = 20

In [39]:
x_ground_truth = np.linalg.solve(A, b)
print(x_ground_truth)
x_minres, norms_resid, norms_deviation, tau_values = minres_scheme(A, b, num_iterations)
print(x_minres)
print(norms_resid)
print(norms_deviation)
print(tau_values)

[ 1.83636625  3.96385796 -0.33252747  2.36315663 -5.20169247  1.81763145
 -3.6043646 ]
[  2835847.24233322 -25178249.8034052    6424042.89947633
 -32631516.46218829 -65803131.39809561  -5613271.41135576
 -17298355.67481428]
[2.940845020983625, 8.985973466410103, 19.666705748376884, 48.13373914501918, 140.0531839274637, 302.94243869738773, 1161.557286357105, 2467.69380614661, 9707.444628877709, 21114.366378711708, 67675.38637053393, 151949.40444738007, 420283.1590812245, 957807.6731413958, 2457376.612427777, 5600161.481505641, 13871515.78408039, 31434526.6920253, 76614187.52644137, 172726522.90335912]
[1.5914788629687953, 4.347081445792003, 9.83537756280898, 25.774112771458075, 61.11067671062513, 179.18627127295701, 522.3509122169894, 1416.8627309983137, 4782.36548739104, 11608.304671731576, 34819.34690371479, 81834.5487429177, 214309.77473643454, 502625.4451801953, 1210470.687926621, 2838446.9375268123, 6559294.964364874, 15402218.692161104, 34976790.74581895, 82441136.5815794]
[1.0, 2